In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, roc_auc_score

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [4]:
df = pd.read_csv("loans_LC (1).csv", low_memory=False)

In [5]:
df.head()

,Unnamed: 0,revol_bal,dti,funded_amnt_inv,revol_util,annual_inc,funded_amnt,loan_amnt,36 months,60 months,B,C,D,E,F,G,delinq_2yrs,loan status
0,0,13648.0,2765.0,4975.0,83.70,24000.0,5000.0,5000.0,1,0,1,0,0,0,0,0,0.0,0
1,1,1687.0,1.0,2500.0,9.40,30000.0,2500.0,2500.0,0,1,0,1,0,0,0,0,0.0,1
2,2,2956.0,872.0,2400.0,98.50,12252.0,2400.0,2400.0,1,0,0,1,0,0,0,0,0.0,0
3,3,5598.0,20.0,10000.0,0.21,49200.0,10000.0,10000.0,1,0,0,1,0,0,0,0,0.0,0
4,4,27783.0,1794.0,3000.0,53.90,80000.0,3000.0,3000.0,0,1,1,0,0,0,0,0,0.0,0

In [6]:
df.shape

(42538, 18)

In [7]:
df.columns

Index(['Unnamed: 0', 'revol_bal', 'dti', 'funded_amnt_inv', 'revol_util',
       'annual_inc', 'funded_amnt', 'loan_amnt', ' 36 months', ' 60 months',
       'B', 'C', 'D', 'E', 'F', 'G', 'delinq_2yrs', 'loan status'],
      dtype='object')

In [8]:
df['loan status'].value_counts()

loan status
0    34116
1     8422
Name: count, dtype: int64

In [9]:
X = df.drop('loan status', axis=1)
y = df['loan status']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [11]:
model1 = LogisticRegression(max_iter=1000)

model1.fit(X_train, y_train)

pred1 = model1.predict(X_test)

print(classification_report(y_test, pred1))

              precision    recall  f1-score   support

           0       0.81      1.00      0.89      6850
           1       0.45      0.01      0.02      1658

    accuracy                           0.80      8508
   macro avg       0.63      0.50      0.45      8508
weighted avg       0.74      0.80      0.72      8508

In [12]:
model2 = RandomForestClassifier()

model2.fit(X_train, y_train)

pred2 = model2.predict(X_test)

print(classification_report(y_test, pred2))

              precision    recall  f1-score   support

           0       0.86      1.00      0.92      6850
           1       0.95      0.34      0.51      1658

    accuracy                           0.87      8508
   macro avg       0.91      0.67      0.72      8508
weighted avg       0.88      0.87      0.84      8508

In [13]:
model3 = GradientBoostingClassifier()

model3.fit(X_train, y_train)

pred3 = model3.predict(X_test)

print(classification_report(y_test, pred3))

              precision    recall  f1-score   support

           0       0.86      1.00      0.93      6850
           1       0.99      0.34      0.51      1658

    accuracy                           0.87      8508
   macro avg       0.93      0.67      0.72      8508
weighted avg       0.89      0.87      0.84      8508

In [14]:
print("Logistic Regression AUC:", roc_auc_score(y_test, pred1))
print("Random Forest AUC:", roc_auc_score(y_test, pred2))
print("Gradient Boosting AUC:", roc_auc_score(y_test, pred3))

Logistic Regression AUC: 0.5029810782492318
Random Forest AUC: 0.669923045089942
Gradient Boosting AUC: 0.6714558918052705

In [15]:
import pandas as pd

results = pd.DataFrame({
    "Model": ["Logistic Regression", "Random Forest", "Gradient Boosting"],
    "AUC": [
        roc_auc_score(y_test, pred1),
        roc_auc_score(y_test, pred2),
        roc_auc_score(y_test, pred3)
    ]
})

results

                 Model       AUC
0  Logistic Regression  0.502981
1        Random Forest  0.669923
2    Gradient Boosting  0.671456